Feature/rla 9
Nikki-021/Refactoring-Life pull request #11
Opened 2024-06-14 02:25 UTC by JuanyVitaloni

2024-06-15 00:11 UTC, erikMaggio requested changes
tenes conflictos en manifest

2024-06-15 03:51 UTC, erikMaggio requested changes

2024-06-15 03:51 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/MainActivityRegister.kt
la clase actvity , la creacion de variables es innecesarias para los binding.edit , agregarlas directamente en la funcion

estas a su vez tienen q estar encapsuladas en un button con setonclicklistener

2024-06-15 03:51 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/MainActivityRegister.kt
agregar saltos de linea al final de la clase

2024-06-15 03:51 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/MainActivityRegister.kt
salto de linea de linea extra en clase viewmodel

2024-06-15 03:51 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/ServiceRegister.kt
crear una data class para body , implementarla en suspened register

2024-06-22 18:54 UTC, erikMaggio requested changes

2024-06-22 18:54 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/MainActivityRegister.kt
la funcion sentInfo , es redundante , quitarla funcion , y implementarla directamente lo que es call , y observer llamarlo en la funcion como prinicipal

se llaman por separado , el oberserver , no se tiene q inicializar cuando se presiona el boton

2024-06-22 18:54 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/ViewModelRegister.kt
mm que son esos loading y error de mutablelivedata???

2024-06-24 14:44 UTC, erikMaggio requested changes

2024-06-24 14:44 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/MainActivityRegister.kt
al momento de realizar el servicio , se tiene q presionar el boton , realizar al accion necesaria para eso , en la funcion de callregister

2024-06-26 20:37 UTC, erikMaggio approved these changes

2024-06-26 20:38 UTC, erikMaggio requested changes
conflictos en diferentes clases , resolver  y commitear

2024-06-29 01:59 UTC, erikMaggio approved these changes

2024-06-29 23:18 UTC, BeatrizGuadalupeDiaz approved these changes

2024-07-01 20:15 UTC, merged