Feature/rla 6.1
Nikki-021/Refactoring-Life pull request #13
Opened 2024-06-22 18:48 UTC by Nikki-021

Subo campos de validaciones

2024-06-24 14:41 UTC, erikMaggio requested changes

2024-06-24 14:41 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/ui/viewmodel/LoginViewModel.kt
no encuentro la necesidad de crear las variables de pass y email y demas en viewmodel (pedirlas por parametro y entregarlas en activity para mas relacion con el editText!)

2024-06-24 14:41 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/ui/viewmodel/LoginViewModel.kt
enn viewmodel , solo crear 2 live data , uno del servicio , otro del state del boton<Boolean>


nada mas

2024-06-24 14:41 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/LoginActivity.kt
el boton al ser un estado livedata , tiene q ser observado y el valr de it , dependiendo el caso tendra el cambio de estado actual , verificar los valores o metodos q se entrega al utilizar un boton con el binding.button

2024-07-08 22:53 UTC, Nikki-021 commented
- subo correcciones de los campos de validación del login
-  Resolucion de conflictos
- agrego cambios al LoginViewModel
- elimino resultState y viewmodelLogin

2024-07-08 23:14 UTC, JuanyVitaloni approved these changes

2024-07-10 16:27 UTC, erikMaggio approved these changes

2024-07-10 16:31 UTC, merged