Feature/rla 13 - desarrollo de la vista home
Nikki-021/Refactoring-Life pull request #14
Opened 2024-06-28 01:34 UTC by BeatrizGuadalupeDiaz

Fondo del home no se ve igual al diseño pero si similar.

2024-06-28 20:30 UTC, erikMaggio requested changes

2024-06-28 20:30 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/ui/adapter/RecyclerViewCategory.kt
nombres de las clases recyclerview prodtuct y category estan mal , serian adapterProduct o productAdapter en su defecto  , revisarlo

2024-06-28 20:30 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/ui/adapter/RecyclerViewProducts.kt
agregar los valores genericos en el item.xml para mostrar los valores repetidos , eliminar la lista mock de activity , para limpieza de codigo

2024-06-28 20:30 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/ui/adapter/RecyclerViewProducts.kt
enviar imagen del diseño terminado , para revision respecto al figma

2024-06-29 01:19 UTC, erikMaggio requested changes

2024-06-29 01:19 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/ui/adapter/Products.kt
agrandar la vista de la foto principal , q abarque un porcentaje mas grande de forma vertical

2024-06-29 01:19 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/ui/adapter/Products.kt
sombreado en el item

2024-06-29 01:19 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/ui/adapter/Products.kt
darle un 20 -80 % en el color degrade

2024-07-02 01:08 UTC, BeatrizGuadalupeDiaz commented on app/src/main/java/com/example/appteam4/ui/adapter/RecyclerViewProducts.kt
Diseño finalizado
![image](https://github.com/Nikki-021/Refactoring-Life/assets/84650163/2d5be114-1a7d-44df-bf58-4f4fc9bc1bf9)

2024-07-02 20:44 UTC, erikMaggio approved these changes

2024-07-02 20:50 UTC, merged