Subo diseño de Login
Nikki-021/Refactoring-Life pull request #4
Opened 2024-06-05 23:08 UTC by JuanyVitaloni

2024-06-06 02:21 UTC, erikMaggio requested changes

2024-06-06 02:21 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/LoginActivity.kt
quitar binding de loginActivity , esto pertenece a otro ticket

2024-06-06 02:21 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/LoginActivity.kt
eliminar saltos de linea de mas

2024-06-06 02:21 UTC, erikMaggio commented on app/build.gradle.kts
quitar las dependencias de gradle , las navegaciones no estan siendo implementadas, y no se la incluye en el ticket

2024-06-06 02:21 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/MainActivity.kt
añadir saltod e linea al final de la clase , eliminar saltos de linea extras , identar el codigo (ctl + A // ctl +alt+ L)

2024-06-06 02:21 UTC, erikMaggio commented on app/src/main/res/drawable/candado.png
nombres en ingles  de todos los png

2024-06-06 02:21 UTC, erikMaggio commented on app/src/main/res/layout/login.xml
modificar el nombre , esto es una activity , por ende tiene q ser , activity_login en su defcto

2024-06-06 02:21 UTC, erikMaggio commented on app/src/main/res/layout/login.xml
utilizar valor genericos para los textos y edittext , match paren o wrap content

2024-06-06 02:21 UTC, erikMaggio commented on app/src/main/res/layout/login.xml
utilizar guide line para evitar tanto margin

2024-06-06 02:21 UTC, erikMaggio commented on app/src/main/res/layout/login.xml
investigar que hacen los tools:ignore , implementarlos solo si hacen falta

2024-06-06 02:21 UTC, erikMaggio commented on app/src/main/res/layout/login.xml
nombre de ids en ingles

2024-06-06 02:21 UTC, erikMaggio commented on app/src/main/res/layout/login.xml
investigar textfield input type para el diseño de los editText

2024-06-06 02:21 UTC, erikMaggio commented on app/src/main/res/layout/login.xml
eliminar los absoluteX

2024-06-06 15:28 UTC, erikMaggio requested changes

2024-06-06 15:28 UTC, erikMaggio commented on app/src/main/res/layout/activity_login.xml
para margenes  horizontales(start y end ) usar horizontal margin , investigar como funciona en el caso q no se conozca

2024-06-06 15:28 UTC, erikMaggio commented on app/src/main/res/layout/activity_login.xml
modificar los margenes de un alto valor, utilizar el anclaje para poder evitar tanto margen

2024-06-06 16:00 UTC, JuanyVitaloni commented
![imagen_2024-06-06_130029675](https://github.com/Nikki-021/Refactoring-Life/assets/167388801/2c34ab5b-10a2-401f-ab42-4c8977931184)

2024-06-06 17:03 UTC, erikMaggio requested changes

2024-06-06 17:03 UTC, erikMaggio commented on app/src/main/res/layout/activity_login.xml
el valor de los margin tiene q estar adaptado a un modelo de patron , ejemplo(los sizie text tiene un tamañano generico en todos los xml que sera de 30 o 14 dependiendo el valor )
modificar elvalor de los margin y textsize comparandolos con preLogin

2024-06-06 17:03 UTC, erikMaggio commented on app/src/main/res/layout/activity_login.xml
los String asignados , tiene q estar en ingles

2024-06-06 17:03 UTC, erikMaggio commented on app/src/main/res/layout/activity_login.xml
la mdoificacion del guideline , debe trabajar con percenty no con begin

2024-06-06 17:03 UTC, erikMaggio commented on app/src/main/res/layout/activity_login.xml
el valor de los pading , debe estar adaptado a un numero redondo ejemplo (10 12 16 20 24)
esto aplica tanto para margin size o padding

2024-06-06 17:03 UTC, erikMaggio commented on app/src/main/res/layout/activity_login.xml
eliminar saltos de linea de mas , identar el codigo

2024-06-06 17:08 UTC, erikMaggio requested changes

2024-06-06 17:08 UTC, erikMaggio commented on app/src/main/res/layout/activity_login.xml
agregar un backgraound white al constraint

2024-06-06 17:08 UTC, erikMaggio commented on app/src/main/res/layout/activity_login.xml
el diseño no cumple con lo solicitado en el figma , redondear los edittext con bordes negros

el texto en la aprte inferior la palabra "registrate aqui , tiene otro estilo de letra"

2024-06-06 17:12 UTC, erikMaggio requested changes

2024-06-06 17:12 UTC, erikMaggio commented on app/src/main/res/layout/activity_login.xml
en los edit text , son labels para la informacion como "email"

2024-06-06 18:47 UTC, JuanyVitaloni commented
![image](https://github.com/Nikki-021/Refactoring-Life/assets/167388801/217f351b-19a2-45bb-b032-1ab6fd22496b)

2024-06-06 22:26 UTC, erikMaggio requested changes

2024-06-06 22:26 UTC, erikMaggio commented on app/src/main/res/layout/activity_login.xml
el nombre de los string para register estan mal , corregirlos

el id registerhere esta mal . necesita su _ entre cada palabra
los colores asignarlos en Colors

2024-06-06 22:26 UTC, erikMaggio commented on app/src/main/res/layout/activity_login.xml
para que utilizas el elevation =  5

2024-06-06 22:26 UTC, erikMaggio commented on app/src/main/res/layout/activity_login.xml
los margin horizontal de 80 , esta muy alto el valor , corregirlo con un mejor anclaje

2024-06-06 22:26 UTC, erikMaggio commented on app/src/main/res/layout/activity_login.xml
asignar el tipo de textStyle , el campo esta agregado pero vacio , asignarle valor o eliminarlo

2024-06-06 22:41 UTC, JuanyVitaloni commented
![image](https://github.com/Nikki-021/Refactoring-Life/assets/167388801/9b67e1d0-675a-453d-9f96-b97acbd2b07b)

2024-06-07 14:30 UTC, erikMaggio requested changes

2024-06-07 14:30 UTC, erikMaggio commented on app/src/main/res/values/strings.xml
string de "resister_here" esta mal escribto
en su defecto , register_here

2024-06-07 14:30 UTC, erikMaggio commented on app/src/main/res/layout/activity_login.xml
el magin de la linea 114 esta correcto??

2024-06-11 15:05 UTC, erikMaggio approved these changes, later dismissed

2024-06-11 17:29 UTC, erikMaggio approved these changes

2024-06-11 17:30 UTC, merged