Feature/rla 4
Nikki-021/Refactoring-Life pull request #5
Opened 2024-06-06 17:16 UTC by Nikki-021

![Captura de pantalla (99)](https://github.com/Nikki-021/Refactoring-Life/assets/135768019/8814ec59-b7f4-46f0-9fa0-e847a945d752)

2024-06-06 17:29 UTC, erikMaggio requested changes

2024-06-06 17:29 UTC, erikMaggio commented on app/src/main/res/drawable/candado.png
nombre de candado y cuenta en ingles

2024-06-06 17:29 UTC, erikMaggio commented on app/src/main/res/drawable/square_buttom.xml
salto de linea al final del codigo en el resource

2024-06-06 17:29 UTC, erikMaggio commented on app/src/main/res/layout/activity_main_register.xml
en los guide line usar percent , y no los begin

2024-06-06 17:29 UTC, erikMaggio commented on app/src/main/res/layout/activity_main_register.xml
los ids de los XML no tienen q tener mayusculas 
email_register en su defecto

2024-06-06 17:29 UTC, erikMaggio commented on app/src/main/res/layout/activity_main_register.xml
los margins , tiene q estar adaptados para seguir un patron con todos los diseños , revisar prelogin y adaptarse a esos valores asignados

2024-06-06 17:29 UTC, erikMaggio commented on app/src/main/res/layout/activity_main_register.xml
el view nose con que proposito esta creado

2024-06-06 17:29 UTC, erikMaggio commented on app/src/main/res/layout/activity_main_register.xml
eliminar saltos de linea de mas
crear un salto de linea al final de la clase xml

2024-06-06 17:29 UTC, erikMaggio commented on app/src/main/res/values/strings.xml
salto de linea al final del resource String

2024-06-06 17:33 UTC, Nikki-021 commented on app/src/main/res/layout/activity_main_register.xml
El view seria el cuadradito que esta al lado de mostrar contraseña, tendría que ser un botón??

2024-06-06 20:18 UTC, Nikki-021 commented
![Captura de pantalla (100)](https://github.com/Nikki-021/Refactoring-Life/assets/135768019/067c15c1-1584-4e02-8bed-d2b5cda6f388)

2024-06-06 21:54 UTC, erikMaggio requested changes

2024-06-06 21:54 UTC, erikMaggio commented on app/src/main/res/layout/activity_main_register.xml
hay un error con los margin

2024-06-06 22:16 UTC, erikMaggio requested changes

2024-06-06 22:16 UTC, erikMaggio commented on app/src/main/res/layout/activity_main_register.xml
los margins tienen que tener un valor mas redondeado ejemplo (10 12 16 20 24)
utilizarlos dependniendo los demas diseños 
esto incluye tanto para margis como para padding y textsize

2024-06-06 22:16 UTC, erikMaggio commented on app/src/main/res/layout/activity_main_register.xml
valores de los percent mas redondeados . en vez de 49 , dale 50
en vez de 61 , 60
revisar los valores

2024-06-06 22:16 UTC, erikMaggio requested changes

2024-06-06 22:16 UTC, erikMaggio commented on app/src/main/res/layout/activity_main_register.xml
chequear los anclajes de los 2 text , para evitar los margins

2024-06-07 14:22 UTC, erikMaggio requested changes

2024-06-07 14:22 UTC, erikMaggio commented on app/src/main/res/layout/activity_main_register.xml
usar percent , borrar begin en los guideline

2024-06-07 14:42 UTC, erikMaggio approved these changes

2024-06-07 14:42 UTC, erikMaggio commented
buen trabajo !

2024-06-07 14:42 UTC, merged