Feature/RLA 8
Nikki-021/Refactoring-Life pull request #8
Opened 2024-06-10 22:41 UTC by BeatrizGuadalupeDiaz

Conexión a la API lista para enlazarla con login, respetando la arquitectura.

2024-06-11 13:59 UTC, erikMaggio reviewed
salto de linea al final de las clases , esto da una impresion de que en un futuro pueda continuar con la ejecuccion de codigo

2024-06-11 14:08 UTC, erikMaggio requested changes

2024-06-11 14:08 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/model/service/HomeService.kt
borrar saltos de linea de mas , agregar un espacio al final de la clase

2024-06-11 14:08 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/model/service/HomeServiceLogin.kt
nombre de la clase esta mal , esto seria LoginService o ServiceLogin

2024-06-11 14:08 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/model/response/ResponseData.kt
este response , no es de data , corresponde a Login

2024-06-11 14:08 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/model/repository/RepositoryLogin.kt
salto de linea de clase a funciones , realizar la separacion de ellas , identar el codigo en todo momento

2024-06-12 14:07 UTC, erikMaggio requested changes

2024-06-12 14:07 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/ui/viewmodel/ViewModelLogin.kt
queda finalizar el consumo de servicio en ActiivityLogin

2024-06-12 23:14 UTC, erikMaggio requested changes

2024-06-12 23:14 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/LoginActivity.kt
la funcion call no deberia harcodear los valores , xq cuando alguien se ingrese , solo corresponde a ese valor q asignas

2024-06-13 00:59 UTC, erikMaggio requested changes

2024-06-13 00:59 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/LoginActivity.kt
esto esta mal , el valor q tener q capturar es el text del edit text y relacionarlo con el valor que ingresa el usuario

entonces tu request te pide email y pass
y esos valores te lo da el usuario al ingresar

2024-06-14 22:52 UTC, erikMaggio requested changes

2024-06-14 22:52 UTC, erikMaggio commented on app/src/main/java/com/example/appteam4/LoginActivity.kt
asd

2024-06-15 01:01 UTC, erikMaggio approved these changes

2024-06-15 01:05 UTC, Nikki-021 approved these changes

2024-06-15 01:07 UTC, merged